#!/bin/sh

# Accelerator for CTranslate2
sudo apt-get install -y libdnnl-dev

# Download M2M-100 model
wget -P models/ https://argos-net.com/v1/translate-en_es-1_0.argosmodel
unzip models/translate-en_es-1_0.argosmodel -d models/

# Download dependencies
git submodule update --init --recursive
